# Generated by Django 4.2 on 2024-11-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nacinalidad',
            new_name='nacionalidad',
        ),
    ]
