# Generated by Django 4.2 on 2024-11-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
