# Generated by Django 4.2 on 2024-11-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='edad',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
